#!/bin/bash

# Check if required variables are set
if [ -z $CORONAFRIEND_DOMAIN ]; then echo '$CORONAFRIEND_DOMAIN Not set - Cannot continue'; exit 1; fi;

# Loop through all CORONAFRIEND_ vars and replace the infiles
for CORONA_VAR in ${!CORONAFRIEND_*}; do echo "${CORONA_VAR}" ; done;
for CORONA_VAR in ${!CORONAFRIEND_*}; do sed -i "s/%${CORONA_VAR}%/$(echo ${!CORONA_VAR} | sed -e 's/\\/\\\\/g; s/\//\\\//g; s/&/\\\&/g')/g" config/* ; done;
for CORONA_VAR in ${!CORONAFRIEND_*}; do sed -i "s/%${CORONA_VAR}%/$(echo ${!CORONA_VAR} | sed -e 's/\\/\\\\/g; s/\//\\\//g; s/&/\\\&/g')/g" scripts/* ; done;
for CORONA_VAR in ${!CORONAFRIEND_*}; do sed -i "s/%${CORONA_VAR}%/$(echo ${!CORONA_VAR} | sed -e 's/\\/\\\\/g; s/\//\\\//g; s/&/\\\&/g')/g" appspec.yml ; done;
