#!/bin/bash

rm -f /var/www/html/index.html
rm -f /var/www/html/index.nginx-debian.html

# Remove existing %CORONAFRIEND_DOMAIN%.html File
if [ -f "/var/www/html/%CORONAFRIEND_DOMAIN%.html" ]; then
    rm -f /var/www/html/%CORONAFRIEND_DOMAIN%.html
fi

# Remove exiting root nginx file
rm -rf /etc/nginx/nginx.conf

rm -rf /var/www/domains/%CORONAFRIEND_DOMAIN%

# Setup Domain Folders
if [ ! -d "/var/www/domains/%CORONAFRIEND_DOMAIN%" ]; then
    mkdir -p /var/www/domains/%CORONAFRIEND_DOMAIN%
fi

if [ ! -d "/var/www/domains/%CORONAFRIEND_DOMAIN%/public" ]; then
    mkdir -p /var/www/domains/%CORONAFRIEND_DOMAIN%/public
fi

if [ ! -d "/var/www/domains/%CORONAFRIEND_DOMAIN%/src" ]; then
    mkdir -p /var/www/domains/%CORONAFRIEND_DOMAIN%/src
fi

if [ ! -d "/var/www/domains/%CORONAFRIEND_DOMAIN%/logs" ]; then
    mkdir -p /var/www/domains/%CORONAFRIEND_DOMAIN%/logs
fi

if [ ! -d "/var/www/domains/%CORONAFRIEND_DOMAIN%/vendor" ]; then
    mkdir -p /var/www/domains/%CORONAFRIEND_DOMAIN%/vendor
fi
