#!/bin/bash

# Remove existing %CORONAFRIEND_DOMAIN%.html File
if [ -f "/var/www/html/%CORONAFRIEND_DOMAIN%.html" ]; then
    rm -f /var/www/html/%CORONAFRIEND_DOMAIN%.html
fi

# Setup Domain Folders
if [ ! -d "/var/www/domains/%CORONAFRIEND_DOMAIN%" ]; then
    mkdir -p /var/www/domains/%CORONAFRIEND_DOMAIN%
fi

if [ ! -d "/var/www/domains/%CORONAFRIEND_DOMAIN%/public" ]; then
    mkdir -p /var/www/domains/%CORONAFRIEND_DOMAIN%/public
fi

if [ ! -d "/var/www/domains/%CORONAFRIEND_DOMAIN%/src" ]; then
    mkdir -p /var/www/domains/%CORONAFRIEND_DOMAIN%/src
fi

if [ ! -d "/var/www/domains/%CORONAFRIEND_DOMAIN%/logs" ]; then
    mkdir -p /var/www/domains/%CORONAFRIEND_DOMAIN%/logs
fi

rm -rf /var/www/domains/%CORONAFRIEND_DOMAIN%